<script setup lang="ts">
import type { SlideNode } from '../core/parser';
import AstRenderer from './AstRenderer.vue';

const props = defineProps<{
  slides: SlideNode[];
  studentName?: string;
  courseName?: string;
  date?: string;
}>();

// 获取当前日期
const displayDate = props.date || new Date().toLocaleDateString();
</script>

<template>
  <div class="homework-container bg-gray-50 dark:bg-gray-900 min-h-screen py-12 px-4">
    <div class="paper-sheet max-w-4xl mx-auto bg-white dark:bg-slate-800 shadow-2xl p-16 font-serif leading-relaxed">
      
      <header v-if="slides.length > 0 && slides[0].type === 'cover'" class="text-center mb-16 border-b-2 border-black dark:border-white pb-8">
        <h1 class="text-4xl font-bold mb-4">{{ slides[0].title }}</h1>
        <div class="flex justify-center gap-8 text-lg italic opacity-80">
          <span>{{ studentName || 'Student Name' }}</span>
          <span>{{ courseName || 'Assignment' }}</span>
          <span>{{ displayDate }}</span>
        </div>
        <div class="mt-6 text-left">
           <AstRenderer v-for="(el, idx) in slides[0].elements" :key="idx" :node="el" />
        </div>
      </header>

      <main class="space-y-16">
        <template v-for="(slide, index) in slides" :key="index">
          <section v-if="slide.type === 'content'" class="question-block">
            
            <div v-if="!slide.isContinuation" class="mb-6">
              <h2 class="text-2xl font-bold mb-4 flex items-baseline">
                <span class="bg-black text-white px-2 py-0.5 mr-3 text-lg dark:bg-white dark:text-black">Problem</span>
                {{ slide.title }}
              </h2>
              <div class="bg-gray-50 dark:bg-gray-700/30 p-6 rounded-lg border-l-4 border-gray-300 italic">
                <AstRenderer v-for="(el, idx) in slide.elements" :key="'q'+idx" :node="el" />
              </div>
            </div>

            <div v-else class="solution-block relative mt-8">
              <div class="flex items-center mb-4 text-teal-700 dark:text-teal-400 font-bold tracking-widest uppercase text-sm">
                <span class="mr-2">Solution</span>
                <div class="flex-1 h-px bg-teal-100 dark:bg-teal-900"></div>
              </div>
              <div class="pl-2">
                <AstRenderer v-for="(el, idx) in slide.elements" :key="'a'+idx" :node="el" />
                <div class="text-right text-xl mt-4">□</div>
              </div>
            </div>

          </section>
        </template>
      </main>

      <footer class="mt-20 pt-8 border-t border-gray-100 text-center text-sm text-gray-400 font-sans">
        Generated by Local Studio · End of Assignment
      </footer>
    </div>
  </div>
</template>

<style scoped>
/* 核心：引入学术风字体栈 */
.paper-sheet {
  font-family: "Latin Modern Roman", "Times New Roman", "Source Han Serif SC", "Noto Serif CJK SC", serif;
  line-height: 1.8;
  color: #1a1a1a;
}

:global(.dark) .paper-sheet {
  color: #e2e8f0;
}

/* 覆盖 AstRenderer 中的一些样式，使其更学术 */
:deep(p) { margin-bottom: 1.25rem; font-size: 1.1rem; }
:deep(code) { font-family: "Fira Code", monospace; font-size: 0.95em; }
:deep(.shiki) { border-radius: 4px !important; box-shadow: none !important; }

/* 打印支持：作业视图最重要的功能 */
@media print {
  .homework-container { padding: 0; background: white; }
  .paper-sheet { box-shadow: none; padding: 0; width: 100%; max-width: none; }
  .solution-block { page-break-inside: avoid; } /* 避免解答被切断 */
}
</style>